### ISSUE TITLE
Best choice of Scheme implementation for exercises?

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xscheme#11]
So far, I'm about 7.8 exercises in implementing the Scheme track in [GNU Guile Scheme](http://www.gnu.org/software/guile/). Since every Scheme implementation has its own idiosyncrasies, I don't see an obvious answer to the question, "which Scheme?". I went with Guile since it's useful, widespread, and actively maintained. The other choice that hits those criteria would be Racket, perhaps, but I feel like it's overkill and expecting people to use the DrRacket environment bothers me.

I considered MIT Scheme, Chibi Scheme, Chicken Scheme, etc., but each present their own similar issues when it comes to package management, module loading, testing, supported SFRI's, etc., so I wanted to start a thread for discussing the "which Scheme" question before it was too late to pivot if there's good reason to do so.

**Comment by wobh** [comment]
I agree with your reasoning so far, but defer to those who are more familiar with the different Scheme implementations.

**Comment by canweriotnow** [comment]
Reading some of the sfri-64 tests for various sfri's, I found some viable ideas for supporting multiple implementations. So I'm going to close this under the aegis of "right now we support Guile, I'd be happy to work on multi-Scheme support down the road."

Comments still wlecome, esp. w/ reasoning to re-open.
