### ISSUE TITLE
Test headers

### ISSUE THREAD

**Issue by canweriotnow** [exercism/xscheme#16]
One of the tedious bits fo creating new exercises is the test header boilerplate.

If we get to the point of supporting multiple scheme dialects, this boilerplate is going to grow, and right now changes to the test runner involve tedious cut/copy/paste or sed/awk/grep/xargs. Not exactly happy friendly. 

So in the 'nice to have' category would be a test header template that could be used to keep all the tests in sync... even if it's a shell script hat lives in the repo root to start with.

**Comment by kytrinyx** [comment]
Yeah, that would be lovely. We can stick it in bin/ since we already have some stuff in there.

**Comment by canweriotnow** [comment]
Ah, sweet. I'll add that to the list.

I think I need an org-mode file just for exercism todos at this point :)

**Comment by kytrinyx** [comment]
My todo lists are so out of control, it's not even funny. The fact that it's lists, plural, is a really bad sign.

**Comment by canweriotnow** [comment]
You _are_ using org-mode, right? I can't imagine managing my life without it.

**Comment by kytrinyx** [comment]
No, I'm not.

**Comment by canweriotnow** [comment]
*feigned horror*

**Comment by canweriotnow** [comment]
Closing, good for now via #17
